(declare-const offense_level Int)
(declare-const criminal_history_category Int)
(declare-const sentence_minimum Int)
(declare-const sentence_maximum Int)
(declare-const zone Int)
(declare-const life_maximum Bool)
(declare-const life_minimum Bool)

(assert (=> (not life_maximum) (not life_minimum)))
(assert (=> (< offense_level 37) (not life_maximum)))
(assert (=> (> offense_level 13) (= zone 4)))

(assert (=>
    (= offense_level 1)
    (and (= sentence_minimum 0) (= sentence_maximum 6) (= zone 1))))

(assert (=>
    (= offense_level 2)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 1) (= sentence_maximum 7) (= zone 2))
        (and (= sentence_minimum 0) (= sentence_maximum 6) (= zone 1)))))

(assert (=>
    (= offense_level 3)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 3) (= sentence_maximum 9) (= zone 2))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 2) (= sentence_maximum 8) (= zone 2))
            (and (= sentence_minimum 0) (= sentence_maximum 6) (= zone 1))))))

(assert (=>
    (= offense_level 4)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 6) (= sentence_maximum 12) (= zone 2))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 4) (= sentence_maximum 10) (= zone 2))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 2) (= sentence_maximum 8) (= zone 2))
                (and (= sentence_minimum 0) (= sentence_maximum 6) (= zone 1)))))))

(assert (=>
    (= offense_level 5)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 9) (= sentence_maximum 15) (= zone 2))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 6) (= sentence_maximum 12) (= zone 2))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 4) (= sentence_maximum 10) (= zone 2))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 1) (= sentence_maximum 7) (= zone 2))
                    (and (= sentence_minimum 0) (= sentence_maximum 6) (= zone 1))))))))

(assert (=>
    (= offense_level 6)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 12) (= sentence_maximum 18) (= zone 3))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 9) (= sentence_maximum 15) (= zone 2))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 6) (= sentence_maximum 12) (= zone 2))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 2) (= sentence_maximum 8) (= zone 2))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 1) (= sentence_maximum 7) (= zone 2))
                        (and (= sentence_minimum 0) (= sentence_maximum 6) (= zone 1)))))))))

(assert (=>
    (= offense_level 7)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 15) (= sentence_maximum 21) (= zone 4))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 12) (= sentence_maximum 18) (= zone 3))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 8) (= sentence_maximum 14) (= zone 2))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 4) (= sentence_maximum 10) (= zone 2))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 2) (= sentence_maximum 8) (= zone 2))
                        (and (= sentence_minimum 0) (= sentence_maximum 6) (= zone 1)))))))))

(assert (=>
    (= offense_level 8)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 18) (= sentence_maximum 24) (= zone 4))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 15) (= sentence_maximum 21) (= zone 4))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 10) (= sentence_maximum 16) (= zone 3))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 6) (= sentence_maximum 12) (= zone 2))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 4) (= sentence_maximum 10) (= zone 2))
                        (and (= sentence_minimum 0) (= sentence_maximum 6) (= zone 1)))))))))

(assert (=>
    (= offense_level 9)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 21) (= sentence_maximum 27) (= zone 4))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 18) (= sentence_maximum 24) (= zone 4))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 12) (= sentence_maximum 18) (= zone 3))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 8) (= sentence_maximum 14) (= zone 2))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 6) (= sentence_maximum 12) (= zone 2))
                        (and (= sentence_minimum 4) (= sentence_maximum 10) (= zone 2)))))))))

(assert (=>
    (= offense_level 10)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 24) (= sentence_maximum 30) (= zone 4))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 21) (= sentence_maximum 27) (= zone 4))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 15) (= sentence_maximum 21) (= zone 4))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 10) (= sentence_maximum 16) (= zone 3))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 8) (= sentence_maximum 14) (= zone 2))
                        (and (= sentence_minimum 6) (= sentence_maximum 12) (= zone 2)))))))))


(assert (=>
    (= offense_level 11)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 27) (= sentence_maximum 33) (= zone 4))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 24) (= sentence_maximum 30) (= zone 4))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 18) (= sentence_maximum 24) (= zone 4))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 12) (= sentence_maximum 18) (zone 3))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 10) (= sentence_maximum 16) (= zone 3))
                        (and (= sentence_minimum 8) (= sentence_maximum 14) (= zone 2)))))))))

(assert (=>
    (= offense_level 12)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 30) (= sentence_maximum 37) (= zone 4))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 27) (= sentence_maximum 33) (= zone 4))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 21) (= sentence_maximum 27) (= zone 4))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 15) (= sentence_maximum 21) (= zone 4))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 12) (= sentence_maximum 18) (= zone 3))
                        (and (= sentence_minimum 10) (= sentence_maximum 16) (= zone 3)))))))))

(assert (=>
    (= offense_level 13)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 33) (= sentence_maximum 41) (= zone 4))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 30) (= sentence_maximum 37) (= zone 4))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 24) (= sentence_maximum 30) (= zone 4))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 18) (= sentence_maximum 24) (= zone 4))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 15) (= sentence_maximum 21) (= zone 4))
                        (and (= sentence_minimum 12) (= sentence_maximum 18) (= zone 3)))))))))

(assert (=>
    (= offense_level 14)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 37) (= sentence_maximum 46))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 33) (= sentence_maximum 41))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 27) (= sentence_maximum 33))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 21) (= sentence_maximum 27))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 18) (= sentence_maximum 24))
                        (and (= sentence_minimum 15) (= sentence_maximum 21)))))))))

(assert (=>
    (= offense_level 15)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 41) (= sentence_maximum 51))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 37) (= sentence_maximum 46))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 30) (= sentence_maximum 37))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 24) (= sentence_maximum 30))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 21) (= sentence_maximum 27))
                        (and (= sentence_minimum 18) (= sentence_maximum 24)))))))))

(assert (=>
    (= offense_level 16)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 46) (= sentence_maximum 57))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 41) (= sentence_maximum 51))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 33) (= sentence_maximum 41))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 27) (= sentence_maximum 33))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 24) (= sentence_maximum 30))
                        (and (= sentence_minimum 21) (= sentence_maximum 27)))))))))

(assert (=>
    (= offense_level 17)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 51) (= sentence_maximum 63))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 46) (= sentence_maximum 57))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 37) (= sentence_maximum 46))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 30) (= sentence_maximum 37))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 27) (= sentence_maximum 33))
                        (and (= sentence_minimum 24) (= sentence_maximum 30)))))))))

(assert (=>
    (= offense_level 18)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 57) (= sentence_maximum 71))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 51) (= sentence_maximum 63))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 41) (= sentence_maximum 51))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 33) (= sentence_maximum 41))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 30) (= sentence_maximum 37))
                        (and (= sentence_minimum 27) (= sentence_maximum 33)))))))))

(assert (=>
    (= offense_level 19)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 63) (= sentence_maximum 78))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 57) (= sentence_maximum 71))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 46) (= sentence_maximum 57))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 37) (= sentence_maximum 46))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 33) (= sentence_maximum 41))
                        (and (= sentence_minimum 30) (= sentence_maximum 37)))))))))

(assert (=>
    (= offense_level 20)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 70) (= sentence_maximum 87))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 63) (= sentence_maximum 78))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 51) (= sentence_maximum 63))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 41) (= sentence_maximum 51))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 37) (= sentence_maximum 46))
                        (and (= sentence_minimum 33) (= sentence_maximum 41)))))))))

(assert (=>
    (= offense_level 21)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 77) (= sentence_maximum 96))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 70) (= sentence_maximum 87))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 57) (= sentence_maximum 71))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 46) (= sentence_maximum 57))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 41) (= sentence_maximum 51))
                        (and (= sentence_minimum 37) (= sentence_maximum 46)))))))))

(assert (=>
    (= offense_level 22)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 84) (= sentence_maximum 105))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 77) (= sentence_maximum 96))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 63) (= sentence_maximum 78))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 51) (= sentence_maximum 63))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 46) (= sentence_maximum 57))
                        (and (= sentence_minimum 41) (= sentence_maximum 51)))))))))

(assert (=>
    (= offense_level 23)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 92) (= sentence_maximum 115))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 84) (= sentence_maximum 105))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 70) (= sentence_maximum 87))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 57) (= sentence_maximum 71))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 51) (= sentence_maximum 63))
                        (and (= sentence_minimum 46) (= sentence_maximum 57)))))))))

(assert (=>
    (= offense_level 24)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 100) (= sentence_maximum 125))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 92) (= sentence_maximum 115))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 77) (= sentence_maximum 96))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 63) (= sentence_maximum 78))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 57) (= sentence_maximum 71))
                        (and (= sentence_minimum 51) (= sentence_maximum 63)))))))))

(assert (=>
    (= offense_level 25)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 110) (= sentence_maximum 137))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 100) (= sentence_maximum 125))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 84) (= sentence_maximum 105))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 70) (= sentence_maximum 87))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 63) (= sentence_maximum 78))
                        (and (= sentence_minimum 57) (= sentence_maximum 71)))))))))

(assert (=>
    (= offense_level 26)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 120) (= sentence_maximum 150))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 110) (= sentence_maximum 137))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 92) (= sentence_maximum 115))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 78) (= sentence_maximum 97))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 70) (= sentence_maximum 87))
                        (and (= sentence_minimum 63) (= sentence_maximum 78)))))))))

(assert (=>
    (= offense_level 27)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 130) (= sentence_maximum 162))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 120) (= sentence_maximum 150))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 100) (= sentence_maximum 125))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 87) (= sentence_maximum 108))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 78) (= sentence_maximum 97))
                        (and (= sentence_minimum 70) (= sentence_maximum 87)))))))))

(assert (=>
    (= offense_level 28)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 140) (= sentence_maximum 175))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 130) (= sentence_maximum 162))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 110) (= sentence_maximum 137))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 97) (= sentence_maximum 121))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 87) (= sentence_maximum 108))
                        (and (= sentence_minimum 78) (= sentence_maximum 97)))))))))

(assert (=>
    (= offense_level 29)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 151) (= sentence_maximum 188))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 140) (= sentence_maximum 175))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 121) (= sentence_maximum 151))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 108) (= sentence_maximum 135))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 97) (= sentence_maximum 121))
                        (and (= sentence_minimum 87) (= sentence_maximum 108)))))))))

(assert (=>
    (= offense_level 30)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 168) (= sentence_maximum 210))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 151) (= sentence_maximum 188))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 135) (= sentence_maximum 168))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 121) (= sentence_maximum 151))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 108) (= sentence_maximum 135))
                        (and (= sentence_minimum 97) (= sentence_maximum 121)))))))))

(assert (=>
    (= offense_level 31)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 188) (= sentence_maximum 235))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 168) (= sentence_maximum 210))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 151) (= sentence_maximum 188))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 135) (= sentence_maximum 168))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 121) (= sentence_maximum 151))
                        (and (= sentence_minimum 108) (= sentence_maximum 135)))))))))

(assert (=>
    (= offense_level 32)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 210) (= sentence_maximum 262))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 188) (= sentence_maximum 235))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 168) (= sentence_maximum 210))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 151) (= sentence_maximum 188))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 135) (= sentence_maximum 168))
                        (and (= sentence_minimum 121) (= sentence_maximum 151)))))))))

(assert (=>
    (= offense_level 33)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 235) (= sentence_maximum 293))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 210) (= sentence_maximum 262))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 188) (= sentence_maximum 235))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 168) (= sentence_maximum 210))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 151) (= sentence_maximum 188))
                        (and (= sentence_minimum 135) (= sentence_maximum 168)))))))))

(assert (=>
    (= offense_level 34)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 262) (= sentence_maximum 327))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 235) (= sentence_maximum 293))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 210) (= sentence_maximum 262))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 188) (= sentence_maximum 235))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 168) (= sentence_maximum 210))
                        (and (= sentence_minimum 151) (= sentence_maximum 188)))))))))

(assert (=>
    (= offense_level 35)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 292) (= sentence_maximum 365))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 262) (= sentence_maximum 327))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 235) (= sentence_maximum 293))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 210) (= sentence_maximum 262))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 188) (= sentence_maximum 235))
                        (and (= sentence_minimum 168) (= sentence_maximum 210)))))))))

(assert (=>
    (= offense_level 36)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 324) (= sentence_maximum 405))
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 292) (= sentence_maximum 365))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 262) (= sentence_maximum 327))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 235) (= sentence_maximum 293))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 210) (= sentence_maximum 262))
                        (and (= sentence_minimum 188) (= sentence_maximum 235)))))))))

(assert (=>
    (= offense_level 37)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 360) life_maximum (not life_minimum)) ; 360-life
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 324) (= sentence_maximum 405) (not life_maximum))
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 292) (= sentence_maximum 365) (not life_maximum))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 262) (= sentence_maximum 327) (not life_maximum))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 235) (= sentence_maximum 293) (not life_maximum))
                        (and (= sentence_minimum 210) (= sentence_maximum 262) (not life_maximum)))))))))

(assert (=>
    (= offense_level 38)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 360) life_maximum (not life_minimum)) ; 360–life
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 360) life_maximum (not life_minimum)) ; 360–life
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 324) (= sentence_maximum 405) (not life_maximum))
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 292) (= sentence_maximum 365) (not life_maximum))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 262) (= sentence_maximum 327) (not life_maximum))
                        (and (= sentence_minimum 235) (= sentence_maximum 293) (not life_maximum)))))))))

(assert (=>
    (= offense_level 39)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 360) life_maximum (not life_minimum)) ; 360–life
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 360) life_maximum (not life_minimum)) ; 360–life
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 360) life_maximum (not life_minimum)) ; 360–life
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 324) (= sentence_maximum 405) (not life_maximum))
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 292) (= sentence_maximum 365) (not life_maximum))
                        (and (= sentence_minimum 262) (= sentence_maximum 327) (not life_maximum)))))))))

(assert (=>
    (= offense_level 40)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 360) life_maximum (not life_minimum)) ; 360–life
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 360) life_maximum (not life_minimum)) ; 360–life
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 360) life_maximum (not life_minimum)) ; 360–life
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 360) life_maximum (not life_minimum)) ; 360–life
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 324) (= sentence_maximum 405) (not life_maximum))
                        (and (= sentence_minimum 292) (= sentence_maximum 365) (not life_maximum)))))))))

(assert (=>
    (= offense_level 41)
    (ite (> criminal_history_category 5)
        (and (= sentence_minimum 360) life_maximum (not life_minimum)) ; 360–life
        (ite (> criminal_history_category 4)
            (and (= sentence_minimum 360) life_maximum (not life_minimum)) ; 360–life
            (ite (> criminal_history_category 3)
                (and (= sentence_minimum 360) life_maximum (not life_minimum)) ; 360–life
                (ite (> criminal_history_category 2)
                    (and (= sentence_minimum 360) life_maximum (not life_minimum)) ; 360–life
                    (ite (> criminal_history_category 1)
                        (and (= sentence_minimum 360) life_maximum (not life_minimum)) ; 360–life
                        (and (= sentence_minimum 324) (= sentence_maximum 405) (not life_maximum)))))))))

(assert (=>
    (= offense_level 42)
    (and (= sentence_minimum 360) life_maximum (not life_minimum)))) ; 360–life for all

(assert (=>
    (= offense_level 43)
    (and life_minimum life_maximum))) ; life for all

; testing
(assert (= offense_level 18))
(assert (= criminal_history_category 1))

(check-sat)
(get-model)
